### ISSUE TITLE
Validator crashes when validating storage resource when versioning is not yet defined

### ISSUE THREAD

**Issue by daniel-cit** [GoogleCloudPlatform/terraform-validator#201]
Affected version: `2021-03-05`
Terraform version used to generate the plan: `v0.13.6`

Terraform-validator crashes when validating storage resource created by [terraform-google-cloud-storage](https://github.com/terraform-google-modules/terraform-google-cloud-storage) when versioning does not have the definitive value in the plan.

Sample terraform configuration to reproduce the issue(*it does not crash if local.name receives a fixed value*):

```terraform
variable "project_id" { type = string }

locals { name = random_string.bucket_name.result }

resource "random_string" "bucket_name" {
  length  = 5
  upper   = false
  number  = true
  lower   = true
  special = false
}

module "gcs_buckets" {
  source     = "terraform-google-modules/cloud-storage/google"
  version    = "~> 1.7"
  project_id = var.project_id
  location   = "US"
  names      = [local.name]
  prefix     = "tst-bucket"
  versioning = { (local.name) = true }
}
```

In the storage module, versioning is defined as:

https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/9f6085e671eea558585f4c5027bd94f1bcdd4a11/main.tf#L50

```terraform
  versioning {
    enabled = lookup(
      var.versioning,
      lower(each.value),
      false,
    )
  }
```

when running terraform-validator it crashes with:

`terraform-validator convert versioning.json`

```console
ERROR: logging before flag.Parse: I0318 15:31:51.719853    2538 convert.go:182] unknown resource: random_string
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraform-google-conversion/google.expandBucketVersioning(...)
        /Users/stephenrlewis/go/pkg/mod/github.com/!google!cloud!platform/terraform-google-conversion@v0.0.0-20210216195227-1ce38a25c0e8/google/storage_bucket.go:163
github.com/GoogleCloudPlatform/terraform-google-conversion/google.GetStorageBucketApiObject(0x41754a0, 0xc000b8c180, 0xc000531200, 0x3b963f9, 0x21, 0xc000012c30)
        /Users/stephenrlewis/go/pkg/mod/github.com/!google!cloud!platform/terraform-google-conversion@v0.0.0-20210216195227-1ce38a25c0e8/google/storage_bucket.go:67 +0x116d
github.com/GoogleCloudPlatform/terraform-google-conversion/google.GetStorageBucketCaiObject(0x41754a0, 0xc000b8c180, 0xc000531200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/stephenrlewis/go/pkg/mod/github.com/!google!cloud!platform/terraform-google-conversion@v0.0.0-20210216195227-1ce38a25c0e8/google/storage_bucket.go:24 +0xf0
github.com/GoogleCloudPlatform/terraform-validator/converters/google.(*Converter).addCreateOrUpdate(0xc000751200, 0xc00072be60, 0x3b6a458, 0x14)
        /Users/stephenrlewis/projects/terraform-validator/converters/google/convert.go:276 +0x1e4
github.com/GoogleCloudPlatform/terraform-validator/converters/google.(*Converter).AddResourceChanges(0xc000751200, 0xc000963fc0, 0x2, 0x4, 0x2, 0x4)
        /Users/stephenrlewis/projects/terraform-validator/converters/google/convert.go:202 +0x4cd
github.com/GoogleCloudPlatform/terraform-validator/tfgcv.ReadPlannedAssets(0x412f1e0, 0xc00004e070, 0x7ffec2ae1c1c, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000646240, ...)
        /Users/stephenrlewis/projects/terraform-validator/tfgcv/planned_assets.go:51 +0x146
github.com/GoogleCloudPlatform/terraform-validator/cmd.glob..func2(0x564d700, 0xc0002f0970, 0x1, 0x1, 0x0, 0x0)
        /Users/stephenrlewis/projects/terraform-validator/cmd/convert.go:54 +0xb2
github.com/spf13/cobra.(*Command).execute(0x564d700, 0xc0002f0930, 0x1, 0x1, 0x564d700, 0xc0002f0930)
        /Users/stephenrlewis/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x564dc00, 0x0, 0x0, 0x0)
        /Users/stephenrlewis/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/stephenrlewis/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/GoogleCloudPlatform/terraform-validator/cmd.Execute()
        /Users/stephenrlewis/projects/terraform-validator/cmd/root.go:74 +0x2d
main.main()
        /Users/stephenrlewis/projects/terraform-validator/main.go:20 +0x25
```

plan.json for this resource is:

```json
{
    "resources": [
        {
            "address": "module.gcs_buckets.google_storage_bucket.buckets[0]",
            "mode": "managed",
            "type": "google_storage_bucket",
            "name": "buckets",
            "index": 0,
            "provider_name": "registry.terraform.io/hashicorp/google",
            "schema_version": 0,
            "values": {
                "cors": [
                    {}
                ],
                "default_event_based_hold": null,
                "encryption": [
                    {}
                ],
                "lifecycle_rule": [],
                "location": "US",
                "logging": [],
                "project": "prj-d-shared-base-bf40",
                "requester_pays": null,
                "retention_policy": [],
                "storage_class": "MULTI_REGIONAL",
                "versioning": [
                    {}
                ],
                "website": [
                    {}
                ]
            }
        }
    ],
    "address": "module.gcs_buckets"
}
```

the  root of this problem maybe be the `nil` check in terraform-google-converter(magic-modules) in the source file indicated by the stacktrace:

https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/9ab40040d220191f015bd1512d2f2020e4ff1183/google/storage_bucket.go#L163

```go
func expandBucketVersioning(configured interface{}) *storage.BucketVersioning {
	versionings := configured.([]interface{})
	if len(versionings) == 0 {
		return nil
	}

	versioning := versionings[0].(map[string]interface{})
...
}
```

the `expandBucketVersioning` does not do the same nil check `|| vs[0] == nil ` that is done in the `expandBucketWebsite` function which has the same structure and does not crashes terraform-validator:

```go
func expandBucketWebsite(v interface{}) *storage.BucketWebsite {
	if v == nil {
		return nil
	}
	vs := v.([]interface{})

	if len(vs) < 1 || vs[0] == nil {
		return nil
	}

	website := vs[0].(map[string]interface{})
...
```

**Comment by daniel-cit** [comment]
After fixing for the versioning we then have the same issue for  the Cors property:

```json
"cors": [
    {}
],
```


terraform-validator output:

```
ERROR: logging before flag.Parse: I0318 21:34:40.471679    7055 convert.go:182] unknown resource: random_string
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraform-google-conversion/google.expandCors(0xc00093a130, 0x1, 0x1, 0x320bdc0, 0xc0006e4240, 0xc0007c4201)
        /home/dandrade/repos/terraform-google-conversion/google/storage_bucket.go:112 +0x566
github.com/GoogleCloudPlatform/terraform-google-conversion/google.GetStorageBucketApiObject(0x4257c20, 0xc000118d50, 0xc00022a000, 0x3ad22b9, 0x21, 0xc000502b10)
        /home/dandrade/repos/terraform-google-conversion/google/storage_bucket.go:79 +0x4d6
github.com/GoogleCloudPlatform/terraform-google-conversion/google.GetStorageBucketCaiObject(0x4257c20, 0xc000118d50, 0xc00022a000, 0x15, 0xc00021cc58, 0xc000353e40, 0xc0007c4280, 0x15)
        /home/dandrade/repos/terraform-google-conversion/google/storage_bucket.go:24 +0xad
github.com/GoogleCloudPlatform/terraform-validator/converters/google.(*Converter).addCreateOrUpdate(0xc0007ec040, 0xc0002813b0, 0x3aa62f3, 0x14)
        /home/dandrade/repos/terraform-validator/converters/google/convert.go:278 +0x1e1
github.com/GoogleCloudPlatform/terraform-validator/converters/google.(*Converter).AddResourceChanges(0xc0007ec040, 0xc000725b60, 0x2, 0x4, 0x2, 0x4)
```

which needs to the solved in the same way.

The properties  **website** and **encryption** already had the guard condition for this situation.
