### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by jenshonkan84** [GoogleCloudPlatform/terraform-validator#81]
Hi

I get this error when running the validator against a plan file that has a google_storage_bucket resource in it.
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraform-google-conversion/google.GetStorageBucketApiObject(0x285e000, 0xc000121d20, 0xc0000fcf00, 0x2470baf, 0x21, 0xc000c8d320)
        /home/jens_hornstrom_seb_se/terraform-validator/vendor/github.com/GoogleCloudPlatform/terraform-google-conversion/google/storage_bucket.go:80 +0x10e4
github.com/GoogleCloudPlatform/terraform-google-conversion/google.GetStorageBucketCaiObject(0x285e000, 0xc000121d20, 0xc0000fcf00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/jens_hornstrom_seb_se/terraform-validator/vendor/github.com/GoogleCloudPlatform/terraform-google-conversion/google/storage_bucket.go:25 +0xdc
github.com/GoogleCloudPlatform/terraform-validator/converters/google.(*Converter).AddResource(0xc000393bf0, 0x2854e80, 0xc00025d980, 0x0, 0x0)
        /home/jens_hornstrom_seb_se/terraform-validator/converters/google/convert.go:157 +0x14c
github.com/GoogleCloudPlatform/terraform-validator/tfgcv.ReadPlannedAssets(0x7fff8c0e872e, 0x16, 0x0, 0x0, 0x0, 0x0, 0xc000229c00, 0x0, 0x0, 0x0, ...)
        /home/jens_hornstrom_seb_se/terraform-validator/tfgcv/planned_assets.go:101 +0x516
github.com/GoogleCloudPlatform/terraform-validator/cmd.glob..func6(0x36f1ce0, 0xc000329520, 0x1, 0x2, 0x0, 0x0)
        /home/jens_hornstrom_seb_se/terraform-validator/cmd/validate.go:52 +0x9b
github.com/spf13/cobra.(*Command).execute(0x36f1ce0, 0xc0003294e0, 0x2, 0x2, 0x36f1ce0, 0xc0003294e0)
        /home/jens_hornstrom_seb_se/terraform-validator/vendor/github.com/spf13/cobra/command.go:762 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x36f1a80, 0x0, 0x0, 0x0)
        /home/jens_hornstrom_seb_se/terraform-validator/vendor/github.com/spf13/cobra/command.go:850 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/jens_hornstrom_seb_se/terraform-validator/vendor/github.com/spf13/cobra/command.go:800
github.com/GoogleCloudPlatform/terraform-validator/cmd.Execute()
        /home/jens_hornstrom_seb_se/terraform-validator/cmd/root.go:77 +0x2d
main.main()
        /home/jens_hornstrom_seb_se/terraform-validator/main.go:20 +0x20
```

Im running this version of validator:
```
Build version: 2019-10-02
```

This is my simple terraform script:

```
### SET FW RULES FOR GOOGLE LB (DEMO)
resource "google_compute_firewall" "allow-gcp-lb" {
  project     = "core-******"
  name        = "allow-gcp-lb-to"
  network     = "core-vpc"
  disabled    = true
  description = "This is a Dummy FW rule to show how to open for gcp load-balancer"
  target_tags = ["dummy"]
  allow {
    protocol = "tcp"
    ports    = ["443"]
  }
  source_ranges = ["130.211.0.0/22", "35.191.0.0/16"]
}

resource "google_storage_bucket" "test-bucket" {
  name     = "test-unti-us-bucket"
  location = "US"
  project = "testproject234-*****"
  labels = {
    "ownerteam"     = "jens"
    "costcenter"    = "apa"

  }

}
```

**Comment by morgante** [comment]
Can you share the commands and Terraform version used?

**Comment by jenshonkan84** [comment]
```
terraform init
terraform plan -out "planfile.tfplan"
terraform show -json ./planfile.tfplan > ./planfile.tfplan.json
terraform-validator validate ./planfile.tfplan.json --policy-path=/opt/forseti-rules --project core-99955
terraform version
Terraform v0.12.9
+ provider.google v2.16.0
```

**Comment by onetwopunch** [comment]
Hi @jenshonkan84 I was able to reproduce the error and created a PR upstream to Magic Modules where the source of the code is located https://github.com/GoogleCloudPlatform/magic-modules/pull/2464

**Comment by onetwopunch** [comment]
@jenshonkan84 This is fixed in the terraform-conversion library: https://github.com/GoogleCloudPlatform/terraform-google-conversion/pull/228
